name: Release
concurrency: ci-release

on:
  push:
    branches:
      - main
      - beta
      - alpha

env:
  semrel_package_command: "npm i semantic-release @semantic-release/changelog @semantic-release/git semantic-release-export-data -D"

jobs:
  get-next-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: ${{ env.semrel_package_command }}
      - run: npx semantic-release --dry-run
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}

  buildtest:
    name: Build, Test & Release
    needs: get-next-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew -Pobl_android_app_versionName=${{ needs.get-next-version.outputs.new-release-version }} -Pobl_android_app_buildNumber=${{ github.run_number }} build

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Java Tests            # Name of the check run which will be created
          path: "**/test-results/**/*.xml"    # Path to test results
          reporter: java-junit        # Format of test results

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install npm release packages
        run: ${{ env.semrel_package_command }}
        
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release