name: 'Test Reports'

on:
  workflow_run:
    workflows: [ 'Tests' ]                     # runs after CI workflow
    types:
      - completed

jobs:
  unittest-report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v2
        with:
          artifact: unittest-results        # artifact name
          name: Unit Tests                  # Name of the check run which will be created
          path: '**/*.xml'                  # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results

  instrumentationtest-report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v2
        with:
          artifact: instrumentationtest-results            # artifact name
          name: Instrumentation Tests       # Name of the check run which will be created
          path: '**/*.xml'                  # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results
