name: Tests

on:
  push:
    branches: [main, beta, alpha]
  pull_request:

jobs:
  buildtest:
    name: Build & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Prepare gradle environment
        run: |
          mkdir -p ~/.gradle
          rm -f ~/.gradle/gradle.properties
          touch ~/.gradle/gradle.properties
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties

      - name: Build with Gradle
        run: ./gradlew build test

      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: unittest-results
          path: "**/test-results/**/*.xml"    # Path to test results

  instrumentedTests:
    name: Instrumented Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Prepare gradle environment
        run: |
          mkdir -p ~/.gradle
          rm -f ~/.gradle/gradle.properties
          touch ~/.gradle/gradle.properties
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties

      - name: Run connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: 'x86_64'
          api-level: 30
          script: ./gradlew connectedAndroidTest

      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: instrumentationtest-results
          path: "**/androidTest-results/**/*.xml"    # Path to test results
